version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: oc_taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vfHRBqR0
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: vfHRBqR0
      DB_NAME: oc_taskdb

volumes:
  pgdata:
